### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by shimbalama** [HKU-BAL/Clair#14]
Hi, I'm getting a rare issue in a small GRCh38 contig (chrUn_KI270336v1) that is making my WDl pipe fall over. In this instance nothing has mapped, but I don't think that that is the issue.

`No read has been process, either the genome region you specified has no read cover, or please check the correctness of your BAM input (/working/genomeinfo/cromwell-dev/cromwell-executions/ONT/7de38df6-2b8b-4c07-b082-8d014fc06cb5/call-clair/shard-136/inputs/1486994909/sampleID.bam).
INFO:tensorflow:Restoring parameters from /reference/software/claire/claire-2.0.6/ont/model
Restoring parameters from /reference/software/claire/claire-2.0.6/ont/model
Calling variants ...
Processed 0 tensors
Total time elapsed: 0.00 s
[INFO] Using 9 CPU threads
Delay 2 seconds before starting variant calling ...
/var/spool/PBS/mom_priv/jobs/10425955.hpcpbs02.SC: line 25: 13868 Alarm clock             clair.py callVarBam --threads 10 --chkpnt_fn /reference/software/claire/claire-2.0.6/ont/model --ref_fn /working/genomeinfo/cromwell-dev/cromwell-executions/ONT/7de38df6-2b8b-4c07-b082-8d014fc06cb5/call-clair/shard-136/inputs/862458108/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa --bam_fn /working/genomeinfo/cromwell-dev/cromwell-executions/ONT/7de38df6-2b8b-4c07-b082-8d014fc06cb5/call-clair/shard-136/inputs/1486994909/sampleID.bam --ctgName chrUn_KI270336v1 --sampleName chrUn_KI270336v1_name --call_fn chrUn_KI270336v1.vcf`

I think it comes from line 203 of https://github.com/HKU-BAL/Clair/blob/90dc1a9c47c1d346b834f0ea54d2e185779f1c8a/clair/callVarBam.py . What is the purpose of the alarm here? It's possible that if my server is smashed that 2 seconds is simply not enough for network lag etc.

What would you suggest as a work around?

Thanks in advance,
Liam

**Comment by aquaskyline** [comment]
Could you please check if there are reads aligned to 'chrUn_KI270336v1'. The alarm is a mechanism to exit all forked processes if one or more processes run in to a problem. In your error message ```No read has been process, either the genome region you specified has no read cover``` shows no read was extracted from 'chrUn_KI270336v1'
