### ISSUE TITLE
How to handle such "duplicate" calls?

### ISSUE THREAD

**Issue by SHuang-Broad** [HKU-BAL/Clair#15]
Hi, 

I am using Clair on my raw ONT reads (human), and found the following two calls that I don't know how to handle. They essentially differ by 1 base. So I hope there's a "merge" module in Clair to post process such "duplicated" calls.

```
chr1	25808786	.	GGAGGTGAGGACAGCTGGGGTGCGACGTGGGGCCCCTCC	G	691	.	.	GT:GQ:DP:AF	0/1:691:31:0.2258
chr1	25808787	.	GAGGTGAGGACAGCTGGGGTGCGACGTGGGGCCCCTCCGC	G	582	.	.	GT:GQ:DP:AF	0/1:582:31:0.3548
```

<img width="927" alt="Screen Shot 2020-02-09 at 5 16 59 PM" src="https://user-images.githubusercontent.com/16310888/74111098-03263280-4b60-11ea-8d37-580af9df07dd.png">

Unfortunately, I cannot share the data.

Thanks!

**Comment by aquaskyline** [comment]
Will investigate and find a method to distinguish homoployer error induced duplication and real overlapped variants.

A quick workaround would be to retain only one copy (preferably the leftmost) of overlapping variants.

**Comment by SHuang-Broad** [comment]
Thanks!

Yes, that's a quick workaround, although one can imagine some kind of threshold need to be defined for which two variants are to be considered "should be the same".
The case will be more complicated when insertions are involved, as one need to compare the inserted sequence as well.

**Comment by chaklim** [comment]
We now added a simple way to deal with those variants, can check on https://github.com/HKU-BAL/Clair/blob/master/docs/POST_PROCESSING.md#handle-overlapping-variants
