### ISSUE TITLE
VCF reporting for haploid samples

### ISSUE THREAD

**Issue by OscarAspelin** [HKU-BAL/Clair#17]
Hi, I recently ran a bacterial sample (nanopore sequenced) through Clair CallVarBam to find variants in a gyrA gene. I used the --haploid flag and the resulting vcf file is shown below. My question is why the genotype (GT) is still reported as 1/1 (suggesting diploidity, no?) instead of only 1? Maybe I misunderstand how the genoype is reported or that the data has evidence that suggests diploidity. Thanks in advance. 

##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=LowQual,Description="Confidence in this variant being real is below calling threshold.">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=INS,Description="Insertion of novel sequence">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=LENGUESS,Number=.,Type=Integer,Description="Best guess of the indel length">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=AF,Number=1,Type=Float,Description="Estimated allele frequency in the range (0,1)">
##contig=<ID=gyrA>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
gyrA	262	.	G	A	1015	.	.	GT:GQ:DP:AF	1/1:1015:188:0.7713
gyrA	491	.	T	TC	516	.	.	GT:GQ:DP:AF	1/1:516:188:0.1596

**Comment by aquaskyline** [comment]
Ah, it's a bug and it should be outputted as '1'. Before a fix, please consider '1/1' as '1'.

**Comment by aquaskyline** [comment]
Fixed in the new version v1.1.
