### ISSUE TITLE
SNP/indel tag in vcf

### ISSUE THREAD

**Issue by pristanna** [HKU-BAL/Clair#18]
Hi,
I would like to ask if there is an option to add a type of variant tag to the vcf file, so I can select the indels easily? If not, do you plan to implement it? 
Thanks a lot in advance, 
Anna

**Comment by aquaskyline** [comment]
According to the VCF format specification, the variant type of a record should be decided by the program that uses VCF, according to the two columns REF and ALT, and possibly other columns if more rules apply. Clair is not going to decide whether a variant is an Indel or not.

A rule of thumb is, when ALT doesn't include a comma, that the length of REF ≠ the length of ALT, it's an Indel. But when ALT includes comma, you will need to split the alternative alleles and compare the length one by one.

**Comment by pristanna** [comment]
Thanks a lot for your reply! I already solved it by applying a simple bash one-liner. And thanks a lot for this variant caller! It is the first one that I was able to use for PacBio data. Easy to install, easy to run and it can nicely distinguish real insertions in homopolymers from sequencing errors!
