### ISSUE TITLE
Somatic and germline

### ISSUE THREAD

**Issue by vahidAK** [HKU-BAL/Clair#19]
Hi @aquaskyline ,
The variants detected by Clair from a tumor sample would be all germline and somatic variants in that tumor sample? is that right?

Thanks,
Vahid.

**Comment by aquaskyline** [comment]
That's correct. Although Clair can identify some somatic variants with allelic fraction ≥0.15, it was not designed for detecting somatic variants, so please use with caution.

**Comment by vahidAK** [comment]
Thanks a lot @aquaskyline
