### ISSUE TITLE
Coverage is less than igv show

### ISSUE THREAD

**Issue by zhenLiuXplr** [HKU-BAL/Clair#25]
Hi Ruibang

I use callVarBam with `--haploid` option to call variants in a small genome (29K). I find the DP in the output VCF is lower than the bam file coverage show in IGV or the result of pysam `pysam.PileupColumn.nsegments` (440 vs 479 on the test site). I have tried both `--stop_consider_left_edge` and `--pysam_for_all_indel_bases` but not work. Do you have any idea?

**Comment by aquaskyline** [comment]
Clair doesn't use the soft-clipped bases. Have you disabled showing the soft-clipped bases in IGV?

**Comment by zhenLiuExplr** [comment]
Yes, I have disabled the soft-clipped view.
Here is the [test](https://github.com/zhenLiuExplr/share/tree/master/clair_test) files I used. You might check it in detail.

The vcf is generated by following command. Coverage difference is on 21707 (441 vs 475).
```
python $clair callVarBam --haploid --chkpnt_fn $model --ref_fn $ref \
--bam_fn $bam --ctgName $contig_name --sampleName "test" --call_fn "test.vcf"
```
![image](https://user-images.githubusercontent.com/47103400/78094873-3a9ab800-7408-11ea-89a8-0fad2190860a.png)
![image](https://user-images.githubusercontent.com/47103400/78095026-8ea59c80-7408-11ea-8b19-7751f27f9b49.png)

**Comment by zhenLiuXplr** [comment]
Yes, I have disabled soft-clip view.
Here is the [test](https://github.com/zhenLiuExplr/share/tree/master/clair_test) files I used. You might check it in details.

The vcf is generated by following command. Coverage difference is on 17707 (443 vs 476)
```
python $clair callVarBam --haploid --chkpnt_fn $model --ref_fn $ref \
--bam_fn $bam --ctgName $contig_name --sampleName "test" --call_fn "test.vcf"
```

![image](https://user-images.githubusercontent.com/47103400/78099608-04b00080-7415-11ea-8183-1f86f8741ca0.png)
![image](https://user-images.githubusercontent.com/47103400/78099888-df6fc200-7415-11ea-9d9d-075405fb549f.png)

**Comment by aquaskyline** [comment]
Please set "-dcov 500" when running `callVarBam.py`. It increases the limit of the number of reads starting at each genome position from the default 250 to 500.
