### ISSUE TITLE
Can I use the model training on PacBio CCS data for PacBio non-CCS data?

### ISSUE THREAD

**Issue by flashton2003** [HKU-BAL/Clair#26]
Hello,

After your suggestion to switch to Clair, I'm exploring the option. However, I see that for PacBio there is only a trained model for CCS data. Since I have some slightly older PacBio data which is not CCS, I'm concerned that this model will not be appropriate for my data, which has a much higher error rate (~15%) than CCS data.

My instinct is that I can't use this model for my non-CCS PacBio data, but I would appreciate your opinion.

Best,

Phil

**Comment by aquaskyline** [comment]
Please try this PacBio model for CLR data
http://www.bio8.cs.hku.hk/clair_models/pacbio/clr/1234567.tar

**Comment by flashton2003** [comment]
Thank you.
