### ISSUE TITLE
Interpretation of quality scores

### ISSUE THREAD

**Issue by flashton2003** [HKU-BAL/Clair#27]
Hello,

I see in the clair pre-print that quality scores are defined as follows:

"The variant quality is calculated as the square of the Phred score of the distance between the largest and the second-largest likelihood values."

Currently, I'm interpreting this as:

If a variant has a quality of 400, then there is a 1 in 100 chance (sqrt(400) = 20, phred score 20 = 1 in 100) that the selected variant was chosen when in reality, the "second choice" variant should have been chosen.

Is this interpretation anywhere near the truth?

Thanks,

Phil

**Comment by aquaskyline** [comment]
Your interpretation is correct.
