### ISSUE TITLE
wget '500 Internal Server Error' when downloading training models

### ISSUE THREAD

**Issue by frabanal** [HKU-BAL/Clair#28]
Installation went well, but when I try wget of the different training models I get the following error:
`
--2020-05-18 15:02:24--  http://www.bio8.cs.hku.hk/clair_models/pacbio/ccs/15.tar
Resolving www.bio8.cs.hku.hk (www.bio8.cs.hku.hk)... 147.8.179.16
Connecting to www.bio8.cs.hku.hk (www.bio8.cs.hku.hk)|147.8.179.16|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-05-18 15:02:24 ERROR 500: Internal Server Error.
`

Regards.

**Comment by aquaskyline** [comment]
The server is now recovered. Please try again.

**Comment by frabanal** [comment]
Thanks for the prompt response. It works now.
