### ISSUE TITLE
Trouble when reproduce the 

### ISSUE THREAD

**Issue by snower2010** [HKU-BAL/Clair#29]
Great Job!

I am running Clair on HG002 [bam file](ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/final/ultra-long-ont_GRCh38_reheader.bam) and estimate its performance against [Truth Variants](ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv3.3.2/GRCh38) by vcfeval in RTG tools. But the performance I got is really poor. The performance index are like around 10%. Even after I remove GA4GH low complexity regions from GIAB's high-confidence regions as described in Supplementary information, the index are still very low. 
So could you please help to provide an script to reproduce you results  or give me some advice?
Many thanks!

**Comment by aquaskyline** [comment]
You might want to take a look at the commands in the supplementary note of Clair's paper.

**Comment by snower2010** [comment]
Thanks for your quick answer! We refer to the supplementary note and code available on the github, but the results still seems un-satisfying. I will be very appreciate if there is not an end-to-end script to reproduce the process from variant calling to performance estimation.
