### ISSUE TITLE
An error when run it.

### ISSUE THREAD

**Issue by ERICBJ2020** [HKU-BAL/Clair#32]
Hi:
I have installed Clair by anaconda3.
When I want to run the clairDemo.sh, I meet an error:
from clair.model import Clair
ImportError: cannot import name 'Clair' from 'clair.model' (unknown location)

Could you help me with this?
Thank

**Comment by aquaskyline** [comment]
Please ensure your anaconda is working properly and you have activated Clair's environment properly. Just in case you haven't done sp, please do not install Clair in your base environment, instead, create a separate environment.
