### ISSUE TITLE
Error when take the output vcf as input for VariantQC

### ISSUE THREAD

**Issue by snower2010** [HKU-BAL/Clair#33]
Hi Ruibang,

Clair is great and I have sucessfully run it and Got output vcf. But I occured an ERROR when take this vcf as input for VariantQC(https://github.com/BimberLab/DISCVRSeq).

The ERROR is as followings: "UNEXPECTED ERROR: The provided VCF file is malformed at approximately line number 2964659: unparsable vcf record with allele GBG, for input source: /input/clair.vcf.gz"

It maybe related to the this issue https://github.com/BimberLab/DISCVRSeq/issues/63.

Could you please give me some clues to avoid this error?

Many thanks!

**Comment by aquaskyline** [comment]
From your descriptions, it seems your VCF contains records with non-ACGT alleles ("GBG" in your example, where B means "not A" I suppose). I'm not sure, but standard VCF seems not supporting abbreviated nucleotides in a single record. You might want to change the base 'B' to one in 'C', 'G' or 'T', or remove the record from the input VCF.

**Comment by snower2010** [comment]
Thanks for your quick resonse! I am also wondering how did these records are introduced into the VCF?
