### ISSUE TITLE
KeyError: '*T'

### ISSUE THREAD

**Issue by loof91** [HKU-BAL/Clair#35]
Hi,
Thank you for a really nice program.
With the release of GIAB 4.x truth sets they seem to have introduced the "*" allele for deletions overlapping a position. Is there any plans to incorporate this in Clair? It is currently throwing a "KeyError: '*T'" when you create the tensors for training.

**Comment by aquaskyline** [comment]
Is it GIAB 4.1 or 4.2?

**Comment by loof91** [comment]
I had the issue when using GIAB 4.2, but the annotation is present in both 4.1 and 4.2.

**Comment by aquaskyline** [comment]
we are working on it. will turn back with an update asap.

**Comment by aquaskyline** [comment]
The codes are updated to support '*' in GIAB v4.1 and v4.2. Updating bioconda needs another two to three days.

**Comment by loof91** [comment]
Perfect, thank you.
