### ISSUE TITLE
Installing without conda nor docker

### ISSUE THREAD

**Issue by arturo-opsetmoen-amador** [HKU-BAL/Clair#36]
Hi,

Is it possible to install Clair via make or pip instead of Conda? I have a "base" docker container where we actively avoid using Conda and I would like to add Clair to the docker. 

Thanks a lot for any advice or pointers!

**Comment by aquaskyline** [comment]
In fact it's easy if you got experience with installing libraries using "yum" or "apt-get", or from source-code. Please refer to https://github.com/HKU-BAL/Clair#option-2-build-an-anaconda-virtual-environment-step-by-step, and substitute "conda install" with other ways that you prefer.
