### ISSUE TITLE
GVCF output

### ISSUE THREAD

**Issue by GuillaumeHolley** [HKU-BAL/Clair#38]
Hello,

Would be possible to add a GVCF output to Clair? GLnexus could be used on the output GVCFs to make a joint VCF afterwards.

Thank you for your help.

Best regards,
Guillaume

**Comment by aquaskyline** [comment]
GVCF output added in Clair2.

**Comment by GuillaumeHolley** [comment]
Great, thanks :) Will try it asap.

**Comment by aquaskyline** [comment]
Clair2 will be available as soon as early 2021. Thank you for your suggestion!

**Comment by GuillaumeHolley** [comment]
Oh my bad, I thought that Clair was the v2 of ClairVoyante. Thank you for your work!

**Comment by YanfengJi** [comment]
Hello,
I am trying to process PacBioCLR data with this version of Clair and hope to get GVCF. As mentioned above, GVCF output was added in Clair2, but I did not find the corresponding parameter in the help document. May I ask what parameters should I use.
Thanks

**Comment by aquaskyline** [comment]
Clair doesn't support GVCF output, please use https://github.com/HKU-BAL/Clair3
