### ISSUE TITLE
trained clair model taking long time to run

### ISSUE THREAD

**Issue by kevyin** [HKU-BAL/Clair#39]
Hi,

I've trained a clair model but the calling seem to take >5hrs to run (I stopped the job)
with one of your provided models it was ~1hr for the same chunk of data.

Do you have any insight why this could be the case?

Thanks

**Comment by aquaskyline** [comment]
As long as the model is properly loaded, the running time is only linear to the size of the chunks you are working on. So please check if 1) the model you trained is having the same size as the pretrained models, 2) your model is properly loaded by Clair, and the calling process started by seeing the messages 'xx variants processed.'
