### ISSUE TITLE
PacBio Subread Data

### ISSUE THREAD

**Issue by agos316** [HKU-BAL/Clair#41]
Hi, 
I see that you uploaded a trained model for CLR data and I was wondering what threshold would be adequate to run for usual circumstances. You have 0.2 for PacBio CSS data, was wondering if this applies for subread data as well ? 

If there is a separate model for subread data could it be uploaded ?

Thank you

**Comment by aquaskyline** [comment]
I would suggest a 0.2 for CLR, although we didn't test intensively on CLR data. And for CCS data, since its quality is continuously increasing, you might lower it to 0.15, and further rely on the QUAL for filtering.

**Comment by agos316** [comment]
Thank you, I will apply that threshold
