### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by Francesc-Muyas** [HKU-BAL/Clair#42]
Hi,
I am running Clair in in ONT data (45X) as specified in  _Call variants in a chromosome_ section and only chromosomes 18, 19,20,21,22,X and Y finished. 

The computation of these jobs spent around 60G of ram and more than 18 hours. However, none of the other chromosomes finished because they required more than 60G when they already run 20h. 

Is there any way to solve this memory problem? 

Thanks for you time,

**Comment by aquaskyline** [comment]
Please use 'callVarBamParallel.py' that will further break down chromosomes into smaller chunks. And run fewer tasks at the same time. Each task (command) is usually capped at 6GB memory consumption.
