### ISSUE TITLE
Bioconda Installation Issues - Error: samtoolssamtools: error while loading shared libraries: libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by zhemingfan** [HKU-BAL/Clair#44]
After following the **Option 1** installation instructions on the [README.md](https://github.com/HKU-BAL/Clair#installation), I attempted to run the [demo](https://github.com/HKU-BAL/Clair#installation) and received the following error messages (samtoolssamtools: error while loading shared libraries: libcrypto.so.1.0.0): 

<img width="1769" alt="Screen Shot 2020-11-09 at 1 30 09 PM" src="https://user-images.githubusercontent.com/43304373/98598700-b490fa80-228f-11eb-9c17-50b77386dfe1.png">

I've noticed similar problems in other issues such as [1](https://github.com/jkkbuddika/RNA-Seq-Data-Analyzer/issues/3), and [2](https://github.com/PacificBiosciences/pbbioconda/issues/85), and was wondering if there were any quick fixes possible with Clair. 

Operating on Linux CentOS 7 aarch64. Clair version 2.1.1 was installed.

**Comment by sbilobram** [comment]
Hi,  
I got an error from samtools when initially installing via conda.  I simlply had to re-install samtools 👍 

**_conda install samtools_**
