### ISSUE TITLE
filtering an ONT VCF Clair generated callset from a bi-modal result

### ISSUE THREAD

**Issue by sbilobram** [HKU-BAL/Clair#46]
The documentation does well to suggest a quality cutoff point "_The best quality cutoff is usually the valley between two peaks plus 50_."  
It looks like the example used in the documentation to illustrate is usingst the MEDIAN point between the valley.  In the histograms an Rscript I am using to produce the histograms  draws the MEAN point.  (although it could be scripted to generate the median I suppose).
Just to be clear, the approximate centerpoint (median) +50, between the peaks  is your suggestioin for a cut-off. Right?

**Comment by aquaskyline** [comment]
Generally yes. Some datasets with a below-average quality might require a higher cutoff.
