### ISSUE TITLE
Source of input BAM file?

### ISSUE THREAD

**Issue by ChristopherRichie** [HKU-BAL/Clair#47]
Hi HKU-BAL, 

I have gotten promising results from using Clairvoyante for variant detection in my Oxford Nanopore seq data.
I am moving forward to install Clair now.

Can you provide guidance on the proper workflow for producing the BAM files for Clair/Clairvoyante input?

In particular, I wonder if any polishing step should be performed prior to variant detection.

I see the ONT training sets were made using minimap2.

Would I need to make a new training set / model if I wanted to use bam files that were produced from the medaka workflow (which presumably adds some polishing)?

Thanks for any guidance and suggestions you can provide.
Chris

**Comment by aquaskyline** [comment]
Install Clair using conda. You need to download new models for Clair. Details are at https://github.com/HKU-BAL/Clair#installation
