### ISSUE TITLE
quality threshold advice

### ISSUE THREAD

**Issue by RichardCorbett** [HKU-BAL/Clair#49]
Hi folks,

I need to set up clair to run on a large set of samples and I would prefer to not manually check the score distribution each time to find the quality threshold.  We are running R9 chemistry promethion flowcells and every sample that we manually check  ends up with a threshold of 750.      Is it safe to use a fixed threshold like this when the same library construction/chemistry/sequencer combination is applied to all samples?

thanks,
Richard

**Comment by aquaskyline** [comment]
At the moment the quality between flowcells even from the same batch can vary significantly. That affects the quality threshold in a way. But generally, setting a fixed threshold works.
