### ISSUE TITLE
Automatically call SNPs for all contigs in fasta file?

### ISSUE THREAD

**Issue by OscarAspelin** [HKU-BAL/Clair#51]
Hi, I have a question regarding the enforced argument to always supply the contig name for SNP calling. Sometimes, one might have a fragmented but still high quality assembly that can be used for SNP calling. In that case, one would have to run SNP calling several times. I guess one alternative would be to concatenate all contigs (but that might affect the performance). A desirable feature would be to have Clair automatically call SNPs for all contigs unless a contig name was provided!

**Comment by aquaskyline** [comment]
have you tried the `--bed_fn` option in `callVarBam.py`?

**Comment by OscarAspelin** [comment]
Ah yes sorry, I now recognized the --includingAllContigs option, thanks!
