### ISSUE TITLE
Demo Error: Missing testingData

### ISSUE THREAD

**Issue by Eurus-Holmes** [HKU-BAL/Clair#53]
At `clairDemo.sh`, `wget 'http://www.bio8.cs.hku.hk/testingData.tar'`, but this link is down - 404 Not Found.

**Comment by aquaskyline** [comment]
the link works now. but that file was prepared for Clairvoyante, and it might not work with Clair without changes.

**Comment by Eurus-Holmes** [comment]
@aquaskyline Thanks for your work! For the `Quick demo`, what changes should I make to these data to adapt to Clair?
