### ISSUE TITLE
Any chance of a clair model trained on guppy >=3.6.0, and on guppy 4.4.2 with bonito?

### ISSUE THREAD

**Issue by oneillkza** [HKU-BAL/Clair#54]
Hi there,

I noticed that your models for ONT variant calling are at least two major basecaller updates behind the state of the art. When we tested clair on some in-house GM24385 data, we actually saw a drop in variant call accuracy when using guppy-bonito basecalls, despite an increase in raw read accuracy.

Is there any likelihood of newer models being produced for the newer, more accurate basecalling?

**Comment by aquaskyline** [comment]
Not likely because we are preparing a new version called Clair3, we don't have a firm release date for it but it should be around May. In the new version, all models are trained on guppy >=3.6.0. Not sure about bonito because not much GIAB data were called using bonito at the moment.

**Comment by oneillkza** [comment]
That's great news re: the new release!

For GIAB data, I'm pretty sure the fast5 are available for download (from the Shasta paper), and guppy 4.4.2 can run Bonito models, if you want to call it yourself.

**Comment by aquaskyline** [comment]
Got it. Will include Guppy 4.4.2 data in the new release.

**Comment by aquaskyline** [comment]
Clair3 is now available at https://github.com/HKU-BAL/Clair3.
