### ISSUE TITLE
Quality cut off determination for CLR data

### ISSUE THREAD

**Issue by agos316** [HKU-BAL/Clair#56]
Hi, 

I have used the model for PacBio subread data that you provided within the issues forum. I have a question regarding the quality distribution for this and choosing the cutoff, as the distribution is different from ONT, CSS, and Illumina Data. 

Is there any way to determine this ?

**Comment by aquaskyline** [comment]
Choosing a quality cutoff is not easy in Clair. Please try out Clair3, in which the quality score is redesigned and has a much smaller range, so a constant and small cutoff score is possible.
