### ISSUE TITLE
Models for guppy v5 basecalled Nanopore data

### ISSUE THREAD

**Issue by flashton2003** [HKU-BAL/Clair#60]
Hello,

Guppy v5 basecaller for Nanopore data seems to give a significant boost to consensus genome accuracy. See [here](https://twitter.com/rrwick/status/1402522207755005956).

Do you have any plans to train a model on readsets generated with this new data?

[Guppy v5 release note](https://community.nanoporetech.com/posts/guppy-v5-0-7-release-note) (nanopore community site, login required).

Thanks!

Phil

**Comment by aquaskyline** [comment]
Please checkout Clair3 that provide models for the latest data https://github.com/HKU-BAL/Clair3/blob/main/docs/guppy5_20220113.md
