### ISSUE TITLE
downsampled BAM cannot download

### ISSUE THREAD

**Issue by shiying-sxu** [HKU-BAL/Clair#64]
I cannot open the downsampled BAM download page。
http://www.bio8.cs.hku.hk/clairvoyante/orginalData_hg003/illumina/HG003.GRCh38.60x.1.bam

How can I still get this file？
Thankyou

**Comment by aquaskyline** [comment]
Please use this link: https://www.bio8.cs.hku.hk/clairvoyante/data_hg003/illumina/HG003.GRCh38.60x.1.bam
