### ISSUE TITLE
Clair force calling using callVarBam calls more number of variants than included in a vcf file. 

### ISSUE THREAD

**Issue by teketelah** [HKU-BAL/Clair#65]
Hello,
The vcf file I used for force calling had 57 million SNVs for whole genome variant calling. Force calling using callVarBam and vcf provided with --call_fn resulted in calling 322 million SNVs. Does force calling mean calling those variants in the vcf file plus additional variants or something is wrong? Normally force calling should only call variants at sites provided in the vcf file. I used the following script:

python clair.py callVarBam --chkpnt_fn "/clair/ont/model" --ref_fn "ref.fasta" --bam_fn "alignment.bam" --threshold "0.2" --minCoverage "4" --pypy "pypy3" --samtools "samtools" --delay "10" --threads "4" --sampleName "sample1" --vcf_fn "all_merged.vcf" --ctgName "$CONTIG_NAME" --call_fn "input.vcf"

Any help please?

**Comment by aquaskyline** [comment]
In Clair
```
'--call_fn': "Output variant predictions"
'--vcf_fn': "Candidate sites VCF file input, if provided, variants will only be called at the sites in the VCF file,  default: %(default)s"
```
You should use --call_fn to define the output filename, and --vcf_fn to define the vcf filename that contains the positions that will be genotyped (force called).

**Comment by teketelah** [comment]
Thanks for the reply! Sorry --call_fn "input.vcf" was a typo should be --call_fn "output.vcf".  "all_merged.vcf" is the candidate sites vcf file input for force calling. But force calling didn't call only at the sites provided in "all_merged.vcf" but more.

**Comment by aquaskyline** [comment]
Besdies, if possible, may I suggest you to switch to using Clair3 with better performance but almost identical usage.

**Comment by teketelah** [comment]
Sure I will use Clair3 going forward.

**Comment by teketelah** [comment]
Sure, I will use Clair3 going forward. Thanks for the reply and info.

**Comment by teketelah** [comment]
Thanks, I will use Clair3 going forward.
