### ISSUE TITLE
About execution error

### ISSUE THREAD

**Issue by macarima** [HKU-BAL/Clair#9]
Hello.

I have experiences with Clairvoyante and Clair v1.
I'm trying to use Clair v2. I installed Clair using Docker, Conda with virual environment as your suggestion.
But I got same error messages from running Clair.

> Delay 0 seconds before starting variant calling ...
>Traceback (most recent call last):
>  File "/home/macarima/bioapps/Clair/clair/../clair.py", line 93, in <module>
>    main()
>  File "/home/macarima/bioapps/Clair/clair/../clair.py", line 87, in main
>    submodule.main()
>  File "/home/macarima/bioapps/Clair/dataPrepScripts/ExtractVariantCandidates.py", line 454, in main
>    make_candidates(args)
>  File "/home/macarima/bioapps/Clair/dataPrepScripts/ExtractVariantCandidates.py", line 349, in make_candidates
>    zero_based_position - (0 if reference_start is None else (reference_start - 1))
>  File "/home/macarima/bioapps/Clair/dataPrepScripts/ExtractVariantCandidates.py", line 27, in evc_base_from
>    return base if base == "N" else BASE2ACGT[base]
>KeyError: 'a'
>samtools view: writing to standard output failed: Broken pipe
>samtools view: error closing standard output: -1
>ExtractVariantCandidates.py or GetTruth.py exited with exceptions. Exiting...

Clair is installed on Ubuntu 16.04 with CUDA 10.
My genome file is repeat masked (soft mask).

How can I care this error? May I ask your help?

Thank you.

With best regards,
Hui-Su Kim

**Comment by macarima** [comment]
I tried to call against genome without repeat masking.
It did not make any errors.
Some updates for repeat masked genome seems to be required.

Best,
Kim

**Comment by aquaskyline** [comment]
Thanks, Kim for reporting the issue.
